//+---------------------------------------------------------------------------
//
//  Copyright (c) Microsoft Corporation. All rights reserved.
//
//  File:   codepage.hxx
//
//  Contents:   Locale to codepage
//
//  History:    08-Jul-96     SitaramR    Created
//
//-----------------------------------------------------------------------------

#if !defined __CODEPAGE_HXX__
#define __CODEPAGE_HXX__


ULONG LocaleToCodepage( LCID lcid );


#endif
