//+-------------------------------------------------------------------------
//
//  Copyright (c) Microsoft Corporation. All rights reserved.
//
//  File:       htmlguid.hxx
//
//  Contents:   Declarations of Html properties
//
//--------------------------------------------------------------------------

#if !defined( __HTMLGUID_HXX__ )
#define __HTMLGUID_HXX__

extern GUID CLSID_Storage;

extern GUID CLSID_SummaryInformation;
const int PID_TITLE = 2;

extern GUID CLSID_HtmlInformation;
const int PID_HREF = 2;
const int PID_HEADING_1 = 3;
const int PID_HEADING_2 = 4;
const int PID_HEADING_3 = 5;
const int PID_HEADING_4 = 6;
const int PID_HEADING_5 = 7;
const int PID_HEADING_6 = 8;

#endif // __HTMLGUID_HXX__

