//+-------------------------------------------------------------------------
//
//  Copyright (c) Microsoft Corporation. All rights reserved.
//
//  File:       pch.cxx
//
//  Contents:   Pre-compiled header
//
//--------------------------------------------------------------------------

#include <windows.h>

#pragma warning(disable: 4512)

#include <filter.h>
#include <global.hxx>
#include <filterr.h>
#include <htmlscan.hxx>

#pragma hdrstop
